name: myfinstocks
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - fastapi
  - uvicorn
  - sqlalchemy
  - pandas
  - pip
  - pip:
    - yfinance
    - python-multipart  # For file uploads
    - reportlab         # For PDF generation (when we add it)
    - APScheduler       # For background jobs (when we add it)